export enum HttpErrorCode {
	OK = "OK",
	CREATED = "CREATED",
	BAD_REQUEST = "BAD REQUEST",
	UNAUTHORIZED = "UNAUTHORIZED",
	FORBIDDEN = "FORBIDDEN",
	NOT_FOUND = "NOT FOUND",
	INTERNAL_SERVER_ERROR = "INTERNAL SERVER ERROR",
}
